feat: wip- added custom edit functionality
drew-harris/stemify-website pull request #5
Opened 2022-01-29 20:39 UTC by DamDam98

feat: added edit capabilities for song meta data (wip)

needs: styling, adding/overwriting new data to songData object (should be easy)

could use help with: getting the font, deciding where to put the picked colors (is there a place for it in songData?), spacing (any tips/thoughts?)

2022-01-29 21:05 UTC, drew-harris requested changes
See first comment

2022-01-29 21:05 UTC, drew-harris commented on src/routes/AdminTicket.svelte
> +  let edit = false;
Basically instead of popping out a form to edit,, Make the form first and think of the spotify api as autofill.

2022-01-29 21:05 UTC, drew-harris commented on src/routes/AdminTicket.svelte
> +      <button on:click={saveEdit}>[SAVE]</button>
See first comment

2022-01-29 21:05 UTC, drew-harris commented on src/routes/AdminTicket.svelte
> +  let songName;
all of these states should have a default value 
EX: 
```
let songName = "";
let colors = ["#FF0000", "#0000FF"];
```

2022-01-29 21:05 UTC, drew-harris commented on src/routes/AdminTicket.svelte
> +  }
If this is something that makes sense for every text box to have, then add it to global css

2022-01-30 11:29 UTC, DamDam98 commented on src/routes/AdminTicket.svelte
> +		border: 0px;
prettier extension said it wont work for svelte files. ive been using the svelte extension for auto-linting. i dont think it was properly set up before, but it should be set up now. lmk if still seems to have issues!

2022-01-30 23:38 UTC, merged